sonar.host.url=https://sonarcloud.io
sonar.organization=darge98
sonar.projectKey=darge98_wallet-insight-frontend
sonar.projectName=Wallet Insights — frontend

sonar.sources=apps,libs
sonar.exclusions=**/*.spec.ts,**/test-setup.ts,**/vite.config.mts,**/eslint.config.mjs
sonar.tests=apps,libs
sonar.test.inclusions=**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/**/lcov.info
